---
resource_types:
- name: git
  source:
    repository: concourse/git-resource
  type: registry-image

resources:
- name: source:libpak
  type: git
  icon: github-circle
  source:
    branch: master
    password: ((github-password))
    uri: https://github.com/paketo-buildpacks/openssl-security-provider.git
    username: ((github-username))

groups:
- name: build
  jobs:
  - release-major
  - release-minor
  - release-patch
  - test

jobs:
- name: test
  public: true
  plan:
  - get: source
    resource: source:libpak
    trigger: true
  - task: test
    file: source/scripts/test.yml

- name:  release-major
  public: true
  plan:
  - get: source
    resource: source:libpak
    passed:
    - test
  - task: release
    file: source/scripts/release.yml
    params:
      BUMP: major
  - put: source:libpak
    params:
      repository: source

- name:  release-minor
  public: true
  plan:
  - get: source
    resource: source:libpak
    passed:
    - test
  - task: release
    file: source/scripts/release.yml
    params:
      BUMP: minor
  - put: source:libpak
    params:
      repository: source

- name:  release-patch
  public: true
  plan:
  - get: source
    resource: source:libpak
    passed:
    - test
  - task: release
    file: source/scripts/release.yml
    params:
      BUMP: patch
  - put: source:libpak
    params:
      repository: source

